### ISSUE TITLE
Typo on line 68 (err.rs)

### ISSUE THREAD

**Issue by ghost** [birkenfeld/rick#2]
Hey 👋🏻 

I love this compiler and follow you guys! Thanks a lot!

just wanted to inform about a little typo mistake on line 68 in src/err.rs ```\n        CORRECT SOURCE AND RESUBNIT\n",```

change to **RESUBMIT**.

Thanks :)

**Comment by birkenfeld** [comment]
Hi Timo, thanks for your report. This "typo" is intentionally copied from ESR's compiler, and he says:
```
I also kept the N in `RESUBNIT'; this is a carefully preserved
   feature of INTERCAL-72.
```
